server:
  port: 7001

#Euraka配置
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称
  client:
    registry-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false
    service-url:  # 监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:7002/eureka/