server:
  port: 9527

spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
  instance:
    instance-id: zuul
    prefer-ip-address: true

info:
  app.name: wzy

zuul:
  routes: #路由
    mydept.serviceId: springcloud-provider-dept #mydept.serviceId 改为 springcloud-provider-dept.serviceId
    mydept.path: /mydept/**