server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.wzy.springcloud.pojo


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#Eureka配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8002